### ISSUE TITLE
Code sample how to set up

### ISSUE THREAD

**Issue by henon** [ScienceSoft-Inc/ViewGestures#1]
I figured it out, but the description how to use is very very hard to understand due to incorrect or misleading formulation in Readme.

Best would be a little code sample how to set up for use in a custom view. The view to be monitored has to be wrapped in a ViewGestures view.  

Working code sample for a custom button that has down and up handlers:

using System;
using System.Collections.Generic;
using Xamarin.Forms;
using ScnViewGestures.Plugin.Forms;

namespace Example {
    public partial class ButtonView : ContentView
    {
        public ButtonView ()
        {
            InitializeComponent ();
            Content = _gestures = new ViewGestures () { 
                HorizontalOptions = new LayoutOptions(LayoutAlignment.Fill, true),
                VerticalOptions = new LayoutOptions(LayoutAlignment.Fill, true),
            };
            _gestures.Content=_button=new Label () { 
                HorizontalOptions = new LayoutOptions(LayoutAlignment.Fill, true),
                VerticalOptions = new LayoutOptions(LayoutAlignment.Fill, true),
                XAlign = TextAlignment.Center,
                YAlign = TextAlignment.Center,
            };
            _gestures.TouchBegan += OnTouchDown;
            _gestures.TouchEnded += OnTouchUp;
        }

```
    Label _button;
    ViewGestures _gestures;

    private void OnTouchDown(object sender, EventArgs args) {

    }

    private void OnTouchUp(object sender, EventArgs args) {

    }
    }
```

}

**Comment by henon** [comment]
the above does not work by the way don't get any touches. how does it have to be set up?

**Comment by levsha-sciencesoft** [comment]
Hi, sorry for delay. I added sample which show how to use this plugin.
If you have some question then write them here or create new issue.
